"""Revision for user update

Revision ID: 07b8512d2609
Revises: e2795f9ba499
Create Date: 2022-11-11 00:45:14.483664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b8512d2609'
down_revision = 'e2795f9ba499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
