"""Fixing

Revision ID: e2795f9ba499
Revises: f8b8465952ae
Create Date: 2022-11-08 23:18:50.162045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2795f9ba499'
down_revision = 'f8b8465952ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
